version: "3.7"

services:
  ui:
    stdin_open: true
    tty: true
    command: bash
    build:
      context: ./
      dockerfile: Dockerfile
      target: ui
    ports:
      - 6006:6006
    volumes:
      - "./packages/ui:/app/packages/ui"
      - "/app/packages/ui/node_modules/"

  posts:
    build:
      context: ./
      dockerfile: Dockerfile
      target: posts
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - "./packages/posts:/app/packages/posts"
      - "/app/packages/posts/node_modules"

  admin:
    build:
      context: ./
      dockerfile: Dockerfile
      target: admin
    command: npm run start
    ports:
      - 3001:3000
    volumes:
      - "./packages/admin:/app/packages/admin"
      - "/app/packages/admin/node_modules"