name: Run Tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: prototype-cache
        uses: actions/cache@v2
        with:
          path: /
          key: prototype-${{ hashFiles('*') }}

      - name: Build & Test
        if: steps.prototype-cache.outputs.cache-hit != 'true'
        run: |
          docker build -t monorepo-image .
          docker run --name monorepo monorepo-image npx lerna run test --no-sort